### ISSUE TITLE
List of habits

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#1]
## Value proposition

As a user
I want to see a list of habits with their associated data
in order to have a clear overview

## Description
![Untitled-2023-04-19-1134](https://user-images.githubusercontent.com/125086329/236154987-e833eff2-9b3f-4452-94a2-29a63abb9507.svg)

## Acceptance criteria

- [x] The HabitList component renders a list of habit items on the homepage
- [x] Each habit item in the list includes the habit name, reason, and feeling
- [x] The list scrolls vertically 

## Tasks

- [x] Create a branch 
- [x] Set Global Styles
- [x] Create Component HabitList
- [x] Create mock data
- [x] Implement minimal styling

**Comment by mbosselmann** [comment]
Hi Felix,
great work! :octocat: But I have some remarks for you to consider:

## Description
- I think the grey background is not needed in your wireframe and could be confusing for others as some use this shading to indicate disabled features
- It would be really cool to see some different example data and not only one. It would be cool to have at least two or three different example habits for a better understanding. :)

## Acceptance Criteria
- "The list is populated with mock data" this is more a task and not a acceptance criterion as you refer to the implementation of your user story from a developer perspective. Your first acceptance criterion already describes that a list with habits is displayed. That is enough 👍 
- if you want to to you can add that "The list scrolls vertically" to describe the behavior of your app more :)

And if you do not want to set a **size** for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by mbosselmann** [comment]
Hi Felix,
could it be that you did not update this user story? I think that I see no difference to the state of this user story that I reviewed yesterday (or?). 🤔

**Comment by mbosselmann** [comment]
Now I can see the updated user story! Thank you for sharing again! ❤️ 

LGTM! 🦊 You rock! 🪨
