### ISSUE TITLE
Implement progress bar

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#11]
## Value proposition

As a user
I want to track my progress on a habit
in order to visually see my progress 

## Description
![UserStory6Update2](https://github.com/FelixJncs/capstone-project/assets/125086329/6ff1f2ae-80b7-46c8-865e-03b99f9da4ed)

## Acceptance criteria

- [x] The progress bar starts with an initial value of 0
- [x] Clicking the button increases the value by 1, up to a maximum of 30 days
- [x] The value of the progress bar is visually represented by the width of the progress bar and an increasing number
- [x] The HabitCard component displays the current value of the progress bar.

## Tasks

- [x] Implement the HabitProgressBar component.
- [x] Add a state variable to track the value of the progress bar.
- [x] Display the initial value of the progress bar.
- [x] Add a button to increase the value of the progress bar when clicked.
- [x] Restrict the maximum value of the progress bar to 30 days.
- [x] Update the visual representation of the progress bar based on its value.
- [x] Render the HabitProgressBar component within the HabitCard component.
 
Size: M

**Comment by mbosselmann** [comment]
Hi Felix,
this one is a cool user story! Looking forward to the implementation of this user story. I have one remark about the handling of your progress bar: for the user it might be hard to know that clicking on the progress bar would change the progress. I would work with an extra button next to the progress bar.

I hope this does help. :)

**Comment by HenrikeStahlhut** [comment]
Hi Felix, nice feature. Just one question: which unit will you use for the progress bar? Days? Because the 30 is kind of random number, if the user has no information in which unit they track (or at least it confused me haha :D) 
Otherwise LGTM

**Comment by MerleMak** [comment]
looks good! Maybe you can rephrase the value proposition from "in order to visually see my progress" to " in order to get visual feedback on how consistent I stay with my habits" But that just details. Other than that looks good!
