### ISSUE TITLE
UserStory7 DataStorage

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#13]
## Value proposition

As a user
I want to have my data stored
in order to access the data later on 

## Description
![UserStory7](https://github.com/FelixJncs/capstone-project/assets/125086329/688bbe57-37ee-498a-bbbf-d9c058d44344)

## Acceptance criteria

- [x] The application utilizes Zustand with persist to store and persist user data
- [x] The stored data can be retrieved and accessed reliably across sessions

## Tasks

- [x] Install Zustand Persist in the application
- [x] Define the Zustand store to hold the user data
- [x] Add progress with a value of 0 to objects 
- [x] Update Increment function

Size: M
