### ISSUE TITLE
UserStory8 HabitStats

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#14]
## Value proposition

As a user
I want to know my longest consecutive streak for each habit.
in order to motivate me to maintain or surpass that streak.

## Description
![UserStory8HabitStats](https://github.com/FelixJncs/capstone-project/assets/125086329/ede2df58-7f21-45d8-be2b-5b07ef9a0d60)

## Acceptance criteria

- [x] The longestStreak and currentStreak are displayed on the HabitStatsPage
- [x] The LongestStreak component accurately identifies the user's longest consecutive streak for each habit
- [x] The streak durations are shown as a numerical value
- [x] The progress can only be incremented once a day

## Tasks

- [x] Create the HabitStatsPage
- [x] Implement currentStreak logic
- [x] Implement the logic to calculate the longest consecutive streak for each habit
- [x] Implement minimal styling  to display the streak duration as a numerical value
- [x] implement logic to restrict the increment of progress

Size: L
