### ISSUE TITLE
UserStory9 HabitScore

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#15]
## Value proposition

As a user
I want to have a score rating for each habit
in order to motivate me to improve

## Description

![UserStory9ScoreSystem](https://github.com/FelixJncs/capstone-project/assets/125086329/33f437fa-9d4d-4e5a-8892-2cb5a5e6bd04)

## Acceptance criteria

- [x] The Overall Habit Score component is displayed on the Habit Stats page
- [x] The component correctly calculates a composite score for each habit
- [x] The HabitScore component is displayed on the HabitStatsPage for every habit

## Tasks

- [x] Create the Overall Habit Score component
- [x] Create the HabitScore component for each habit
- [x] Implement the logic to calculate the habit scores
- [x] Implement minimal styling

Size: M
