### ISSUE TITLE
UserStory10 Navbar

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#19]
## Value proposition

As a user
I want a navbar that is always visible on all pages
in order to navigate easily between pages

## Description
![UserStory10](https://github.com/FelixJncs/capstone-project/assets/125086329/70df1385-c41e-496b-b39f-95b60a856bc9)

## Acceptance criteria

- [x] The navbar component should be consistently visible on all pages of the application.
- [x] All Links should lead to the corresponding page

## Tasks

- [x] Implement a navbar component that remains visible on all pages
- [x] Create links within the navbar to navigate to the pages
- [x] Implement Styling
- [x] Implement Icons 

Size: M
