### ISSUE TITLE
Habit Details Page

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#2]
## Value proposition

As a user
I want to see my habit details
in order to better understand them.

## Description
![HabitDetails](https://user-images.githubusercontent.com/125086329/236235030-1d7a8f52-b06c-4eb7-9897-ed655e49ed21.svg)

## Acceptance criteria

- [x] Each habit has its own details page 
- [x] Each page shows the habit name, reason and feeling.
- [x] The user gets via Link to the details page and back to the habit list

## Tasks

- [x] Create a branch 
- [x] Component/HabitDetailsPage
- [x] Make dynamic routes via id
- [x] Create Links to details page and back
- [x] Implement basic styling

**Comment by JessicaLoers** [comment]
**Hey @FelixJncs** ✌️
nice user story! I have some suggestions for you to consider before moving forward.


## Value Proposition
Regarding the value proposition, my first expectation was that the details of my habit would show me a way to get rid of this in addition to the reason and feelings.

I would like to suggest that you delete the **and get rid of them"** part for this user story and make it a separate user story in the future:  Mareike told me that you are planning a Progress Bar to track and to get rid of the bad habits, this would be a perfect match. 😉

## Description
Is the headline **HabitDetails** just the headline of your wire frame, or an actual headline in your app?

If it is part of your app you would need to list it in your Acceptance Criteria, if not I would suggest delete it from the wire frame. 

## Acceptance criteria
➡️ _You could invest some more brainpower here, I'm quite sure you'll find more criteria here_ 
- how does the user get to the details page of the respective habit? 
- how does the user get back to the list of all habits?

Even if the changes feel like a pain at first 😁, you'll be much more productive with a well-designed user story.

**Comment by FelixJncs** [comment]
Hi Jessica, thank you for the advice! 😀 The Idea for a "How to get rid of Them" part is much appreciated 🤩

**Comment by mbosselmann** [comment]
Hi Felix,
you rock! 🪨 LGTM! 🦊
