### ISSUE TITLE
Add habit page

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#3]
## Value proposition

As a user
I want to add new habits
in order to overcome them

## Description
![AddHabitPage](https://user-images.githubusercontent.com/125086329/236424950-e9911c92-293c-4440-8b0a-3641ac40dc35.svg)

## Acceptance criteria

- [x] The AddHabitPage component renders a form with inputs for the "name", "reason", "feeling" and "how to overcome" 
- [x] The form includes a submit button to add the habit to the user's list of habits 
- [x] When the user clicks the button the habit is added to the habit list 
- [x] The "back" link redirects to the habit list 

## Tasks

- [x] Create component/ AddHabitPage
- [x] Add input fields for the habit "name", "reason", "feeling" and "how to overcome" to the form.
- [x] Add a submit button to the form.
- [x] Write a function to handle form submission and add the habit to the user's list of habits.
- [x] Add any necessary validation to the form inputs.
- [x] Add "back" link
- [x] Add minimal styling to the AddHabitPage component

**Comment by t0bbl** [comment]
LGTM
Minor detail: maybe you could redirect the user to the habit list when he submits a new habit. Just a little more convenient.
