### ISSUE TITLE
Delete habits from HabitList

### ISSUE THREAD

**Issue by FelixJncs** [FelixJncs/capstone-project#8]
## Value proposition

As a user
I want to be able to delete a habit
in order to keep the habit list accurate

## Description
![UserStory5](https://github.com/FelixJncs/capstone-project/assets/125086329/519c563d-f4db-4201-a053-1232a2148fa2)

## Acceptance criteria

- [x] The HabitCard component should have a delete button
- [x] Clicking the delete button should remove the corresponding HabitCard from the HabitList
- [x] Clicking on the delete button should delete the corresponding habit from the Zustand store

## Tasks

- [x] Add a delete button to the HabitCard component
- [x] Implement a delete function in Zustand to delete the corresponding habit from the store
- [x] Implement logic to remove the corresponding HabitCard from the HabitList when the delete button is clicked
- [x] Add minimal styling

Size: M

**Comment by doctype-Melvin** [comment]
lgmt
